---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: i want to launch ec2 instance
    ec2:
     aws_access_key: AKIAR4M5SM24SKG6NVMN
     aws_secret_key: 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
     instance_type: t2.micro
     key_name: virginia
     image: ami-0b786a1a999c4e98e
     region: us-east-1
     group: default
     count: 1
     vpc_subnet_id: subnet-3ab35065
     wait: yes
     assign_public_ip: yes