---
- hosts: localhost
  tasks:
  - name: i want to launch ec2 instance
    ec2:
     instance_type: t2.micro
     key_name: virginia
     image: ami-0b786a1a999c4e98e
     region: us-east-1
     group: ansible
     count: 1
     vpc_subnet_id: subnet-3ab35065
     wait: yes
     assign_public_ip: yes